services:
  - docker

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose up -d
  - sleep 10

script:
  - docker exec -it netflux yarn test --forceExit

deploy:
  provider: script
  script: bash -c "docker push aminehmida/netflux &&\
                   docker tag aminehmida/netflux aminehmida/netflux:$TRAVIS_TAG &&\
                   docker push aminehmida/netflux:$TRAVIS_TAG"
  on:
    tags: true
    branch: master
