services:
  - docker

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make start-prod
  - sleep 10

script:
  - make test

deploy:
  provider: script
  script: make push-image
  on:
    tags: true
    branch: master
