version: "2"

services:
  netflux:
    env_file:
      - .env
    container_name: netflux
    restart: always
    build: .
    ports:
      - 80:3000
    links:
      - mongo
    volumes:
      - netflux-install:/usr/src/app
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ../netflux/data:/data/db:rw

volumes:
  netflux-install: {}
