version: "2"

services:
  netflux:
    container_name: netflux
    restart: always
    build: .
    ports:
      - 80:3000
    links:
      - mongo
    volumes:
      - netflux-install:/usr/src/app

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

volumes:
  netflux-install: {}
