version: "2.1"

services:
  netflux:
    env_file:
      - .env
    container_name: netflux
    restart: always
    build: .
    image: aminehmida/netflux:${TRAVIS_TAG:-latest}
    ports:
      - 80:3000
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.0.9
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db:rw
